-- Tecknuovo Risk Framework 5x5 v1.1 (Apr 2026) - full incorporation into the
-- classifier's knowledge store (Chloe's document, received 19 Aug). Workflow 1
-- injects tn_knowledge.risk_framework into every classification, so this takes
-- effect on the next call with no workflow change. The band arithmetic in
-- workflow 1 (Critical 20-25, High 12-19, Medium 8-11, Low-Medium 4-7, Low 1-3)
-- already matches v1.1 and is unchanged.

UPDATE tn_knowledge SET content = 'Tecknuovo 5x5 risk framework v1.1 (Apr 2026). Score = Likelihood (1-5) x Impact (1-5), assessed on an INHERENT basis (before treatment) - signals from calls are always inherent scores.

LIKELIHOOD: 5 Almost Certain (will occur in most circumstances; controls unlikely to prevent; expected more than once a year). 4 Likely (will probably occur; once a year or more). 3 Possible (might occur; has happened in comparable organisations; once every 1-5 years). 2 Unlikely (could occur but not expected; requires unusual circumstances). 1 Rare (only in exceptional circumstances). Be conservative: 5 requires an explicit quote showing it is already happening or virtually certain; a vague or hedged worry is 3 at most.

IMPACT is assessed across FOUR dimensions and the HIGHEST dimension is the rating. 5 Severe: loss >GBP 5m or existential threat; business-wide shutdown >4 weeks; national press, CEO/board resignation risk; criminal prosecution or licence/certification loss. 4 Significant: loss GBP 1m-5m; major function offline 2-4 weeks; sustained negative press or major client loss; regulatory investigation or significant fine. 3 Moderate: loss GBP 250k-1m; partial function offline 1-2 weeks; industry coverage or client concern; formal regulatory action or minor fine. 2 Minor: loss GBP 25k-250k; service degradation days to a week; social media or local coverage, complaint; regulatory notice. 1 Negligible: loss <GBP 25k; disruption <1 day; internal complaint only; minor non-conformance.

BANDS AND APPETITE (score -> band -> required response): 20-25 CRITICAL - zero tolerance, immediate escalation, board agenda item, immediate action plan. 12-19 HIGH - minimal tolerance, active mitigation required, CLOO review within 2 weeks, treatment plan to board. 8-11 MEDIUM - moderate tolerance, controls maintained, monthly monitoring, CLOO-level ownership. 4-7 LOW-MEDIUM - tolerable, monitor and review quarterly, function-level ownership. 1-3 LOW - acceptable, accept and record, annual review. Reserve Critical for risks the managing director must personally see. Customer portfolio risks escalate to MD and CLOO within one week; operational delivery risks escalate to MD at Moderate impact or above.

THE 14 CATEGORIES (Apr 2026 - Technology and AI are now separate) with calibration anchors (impact level 3 / level 5 in Tecknuovo context): 1 Strategic & Commercial (3: loss of a material GBP 1m-5m contract or missed annual growth target; 5: revenue drops >30%, business model questioned). 2 People & Key Person (3: loss of a senior function head or critical knowledge gap; 5: simultaneous loss of CEO/CLOO/MD, delivery capability critically impaired). 3 Information Security & Cyber (3: limited client data breach, ISO 27001 non-conformance, regulatory notification; 5: network compromise, sensitive public-sector data exfiltrated). 4 Regulatory & Compliance (3: HMRC IR35 investigation, ICO notice, ISO certification suspended; 5: multi-regulator enforcement, debarment from public sector procurement). 5 Supplier & Third-Party (3: key freelancer supply disruption or contractor circumvention incident; 5: supply chain collapse across programmes, litigation). 6 Operational Delivery (3: programme delay >4 weeks, SLA breach, penalty clause triggered; 5: CNI delivery failure, public harm, termination for cause). 7 Financial & Economic (3: client payment dispute GBP 100k-500k or client administration risk; 5: top-3 client insolvency, liquidity crisis). 8 Technology - infrastructure and platforms (3: core platform degradation affecting multiple teams, shadow IT incident; 5: systematic data loss, critical system down during live CNI delivery). 9 Business Continuity (3: loss of primary office 1-2 weeks, client SLAs at risk; 5: severe infrastructure loss, no DR, critical service failure). 10 Reputational (3: industry press coverage of a delivery issue; 5: sustained national coverage, Zero Dependency brand irreparably damaged). 11 ESG & Sustainability (3: B-Corp submission rejected or CSRD reporting gap; 5: B-Corp revoked, public sector exclusion on ESG grounds). 12 Portfolio & Customer Concentration (3: loss of one major account, 2-3 months to backfill; 5: top client >40% of revenue exits). 13 Growth & Integration (3: finance function build-out stalls, audit readiness impacted; 5: rapid scale-up triggers ISO non-conformances and client trust loss together). 14 Artificial Intelligence (3: confidential client data submitted to a public AI model, possible client notification, UK GDPR risk; 5: systematic AI misuse causes critical failure in a CNI-adjacent programme, enforcement action, certifications revoked).'
WHERE key = 'risk_framework';
